on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  deploy-react-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install  # or 'yarn install' if you're using Yarn

      - name: Build the React app
        run: npm run build  # Make sure your package.json has a build script

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "philkrause"
          git config user.email "philkrause@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/*
          cp ../CNAME .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
